name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_backend:
    name: build backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    - run: dotnet build --project backend/SwaggerRestApi/SwaggerRestApi

